name: f2f
description: COVID-19 inspired video chat.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_webrtc:
    path: ../flutter-webrtc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
